question_data = [
    {"text": "Pikachu is an Electric-type Pokémon.", "answer": "True"},
    {"text": "Charizard evolves directly from Bulbasaur.", "answer": "False"},
    {"text": "Water-type Pokémon are strong against Fire-type Pokémon.", "answer": "True"},
    {"text": "Ash Ketchum is from the Sinnoh region.", "answer": "False"},
    {"text": "Meowth can speak human language.", "answer": "True"},
    {"text": "Mewtwo is a Psychic-type Pokémon created from Mew's DNA.", "answer": "True"},
    {"text": "There are 898 Pokémon species as of Generation VIII.", "answer": "True"},
    {"text": "Flying-type Pokémon are weak against Rock-type moves.", "answer": "True"},
    {"text": "In Pokémon Go, you can catch Pikachu wearing a hat.", "answer": "True"},
    {"text": "Gengar evolves from Haunter.", "answer": "True"},
    {"text": "Ditto can transform into any Pokémon it sees.", "answer": "True"},
    {"text": "Eevee has three possible evolutions.", "answer": "False"},
    {"text": "Grass-type Pokémon are weak to Water-type moves.", "answer": "False"},
    {"text": "The Pokémon League is the final challenge for trainers in every game.", "answer": "False"},
    {"text": "Psyduck has headaches that lead to powerful psychic abilities.", "answer": "True"},
    {"text": "The Pokémon Center is where trainers go to buy Poké Balls.", "answer": "False"},
    {"text": "Ash's first Pokémon was a Charmander.", "answer": "False"},
    {"text": "Zubat is known for its echolocation abilities.", "answer": "True"},
    {"text": "Pokémon battles can only be fought in gyms.", "answer": "False"},
    {"text": "In Pokémon, the move 'Splash' does damage.", "answer": "False"},
    {"text": "The Pokémon Caterpie evolves into Metapod.", "answer": "True"},
    {"text": "Legendary Pokémon are often found in the wild.", "answer": "False"},
    {"text": "Dragon-type Pokémon are weak to Fairy-type moves.", "answer": "True"},
    {"text": "Alakazam can learn the move 'Teleport'.", "answer": "True"},
    {"text": "The Pokémon Jigglypuff is known for its singing.", "answer": "True"},
    {"text": "Onix is a Rock/Ground-type Pokémon.", "answer": "True"},
    {"text": "Miltank is known for its ability to produce milk.", "answer": "True"},
    {"text": "Lucario is a Fighting/Steel-type Pokémon.", "answer": "True"},
    {"text": "Porygon can evolve into Porygon-Z directly.", "answer": "False"},
    {"text": "The move 'Hyper Beam' requires recharging after use.", "answer": "True"},
    {"text": "Gardevoir can mega evolve.", "answer": "True"},
    {"text": "Pokémon can only evolve when they reach a certain level.", "answer": "False"},
    {"text": "The Pokémon Snorlax is known for blocking roads.", "answer": "True"},
    {"text": "Fire-type moves are ineffective against Water-type Pokémon.", "answer": "True"},
    {"text": "Machoke evolves into Machamp when traded.", "answer": "True"},
    {"text": "The Pokémon Team Rocket is known for their motto.", "answer": "True"},
    {"text": "Togepi is a Dragon-type Pokémon.", "answer": "False"},
    {"text": "Shiny Pokémon have different colorations than their normal counterparts.", "answer": "True"},
    {"text": "Electric-type moves are strong against Ground-type Pokémon.", "answer": "False"},
    {"text": "The Elite Four is the final test for trainers in Pokémon games.", "answer": "True"},
    {"text": "Rayquaza is a Fire-type Pokémon.", "answer": "False"},
    {"text": "Fighting-type Pokémon are weak against Psychic-type moves.", "answer": "True"},
    {"text": "Mew is known for its ability to learn all TM moves.", "answer": "True"},
    {"text": "Beldum evolves into Metang at level 20.", "answer": "False"},
    {"text": "Dark-type Pokémon are weak against Fairy-type moves.", "answer": "True"},
    {"text": "There are only 151 Pokémon in the first generation.", "answer": "False"},
    {"text": "Elekid is an Electric-type baby Pokémon.", "answer": "True"},
    {"text": "Palkia is known as the Pokémon of time.", "answer": "False"},
    {"text": "Shaymin has a Sky Forme.", "answer": "True"},
    {"text": "Charizard can Mega Evolve into two different forms.", "answer": "True"},
    {"text": "The Pokémon Bulbasaur is a Grass/Poison-type.", "answer": "True"},
    {"text": "Pikachu can evolve into Raichu using a Thunder Stone.", "answer": "True"}
]
